travis:
  secure:
    BINSTAR_TOKEN: DjgZ1Ux/puF9xZyEEzQ23Y3YDBvCNxG/ZEEvtUOxt95i5c62TgsMhx66wf+FBm4ZA/qItCJiy3o2W+PSCsEO7VBR9NMzUIdyx+apZozhn8NTqwuoBzcUDrAfR2GkRMwgEIPBuggOaapSWVoi4wANcvBvTSeTx9A90kgWyeDnIQszqO+70DdoYkQb4FxBwkyIkHPIrqY33Nlw8ZmsWlf95wZDAp4Xwd7l2uqZVhpGF4XdTXfgjDr9LPGucdOS/GguV+XjK2RAgIqPJlgussfw4iBjPSXuKkuz7A8GPLMJqhMkuqGOjG0MawOmjbSbKuZa6e8OC1ehgaIq28bUKBU6xvknuhC/yeDqAEOHdRI875CjFbUCn52OsFddDUvybtd1FyagsRCdvSmsUnBzCh1BOj+Yucf9Fd+7pzHxm+pPoEDI1AwFph2l8YpSCOYLKkP7rmYUUfQ4m6zmi4M1MfBgad6QmUu9U6Ckst2PvKtb3rIXjnbSwcYf0v6wzhOLF2wFRJZAtshXcQ7fL7RAsKq2Jq1evpgNIA8v5/qceqXOksgw3o/rRKhSjPhkj8logxqZXH5wSWdicRrBun8B41DpNE7KNgH0cVwKZht8XUyExrnBD4E5zb32uF95KuRcp6+iJMBhhfUkIuC0ILSTwCkvY+u507E2Sh/erevOVhNjFWM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
